### ISSUE TITLE
Syntax/Runtime errors

### ISSUE THREAD

**Issue by pd-448482** [jkaberg/tExtractor#2]
So tried to run this and noticed that nothing was running. Looked at `deluged.log` file in my docker container and saw syntax errors around line 101. Then fixed that and go runtime errors around the use of shutil. Below is the diff of the changes I made to fix the errors.

```
9c9
< import shutil
---
> from shutil import which
44c44
<         exec_path = shutil.which(util)
---
>         exec_path = which(util)
100c100
<                 logger.debug('Moveing file: {0} to: {1}'.format(f, out_dir))
---
>                 logger.debug('Moveing file: {0} to: {1}'.format(f, out_dir)
102c102
< 
---
>    
```

I'm still trying to figure out how to work around the use of the temp dir in a docker container. Without making my docker image large enough to handle the size of any movie extracted, it will fail because of running out of space. 

EDIT:
Found a quick workaround for getting the extraction out of the docker image. 
`temp_dir = tempfile.mkdtemp(dir='/downloads/tmp')`. Just forced the temporary directory to be inside a directory that was already mounted to somewhere outside the container.

**Comment by mattany** [comment]
Hey, I also noticed that nothing was happening when running after downloads finish in qBittorrent v4.2.2. I ran it manually to see what happens to some file and got the following runtime error. I think it is connected:
```
Transcend/Torrents/Completed/Mr.Robot.S04E13.1080p.BluRay.x264-ROVERS"
  File "extract.py", line 101
    shutil.move(os.path.join(temp_dir, f), out_dir)
         ^
SyntaxError: invalid syntax
```

**Comment by pd-448482** [comment]
Yeah. Look at my diff above. Line 9 goes to `import shutil` and line 44 goes to `exec_path = shutil.which(util)`. This is just that the import is only importing one method when 3 different methods are used.

**Comment by mattany** [comment]
True. Although somehow even after importing I get the same error. Also it seems like my system doesn't recognize ```logger``` and ```parser``` for some reason. I don't understand how the author got this code to run

**Comment by pd-448482** [comment]
Well `logging` and `argparse` are part of vanilla python. So may be something with your python environment. I've had it working with the changes in the my original comment.

**Comment by mattany** [comment]
I found the issue! It was the dumbest thing. Took a while but at last I found a missing close-brackets one line before the place where the error is:
```
                logger.debug('Moveing file: {0} to: {1}'.format(f, out_dir))
```
I'll issue a pr with your fix and this one :)

**Comment by jkaberg** [comment]
Thanks, fixed with https://github.com/jkaberg/tExtractor/commit/1fae166a75eaee8ddaf9fd8b6e8195fa0374b85f
