### ISSUE TITLE
logger.warn deprecated

### ISSUE THREAD

**Issue by hr1232** [jkaberg/tExtractor#9]
With current pything versions, the script causes deprecation warnings, e.g.
```
/config/extract.py:111: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('This must be a single file torrent, exiting!')
```
Please consider replacing `logger.warn` by `logger.warning` in lines 73, 112 and 119.

**Comment by jkaberg** [comment]
fixed in https://github.com/jkaberg/tExtractor/commit/463960af88302894d27a87dd2b8a3cc2cc2de4e6
